# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release_x64)
  Brimstone_config = release_x64
  UnitTests_config = release_x64
endif
ifeq ($(config),release_x32)
  Brimstone_config = release_x32
  UnitTests_config = release_x32
endif
ifeq ($(config),debug_x64)
  Brimstone_config = debug_x64
  UnitTests_config = debug_x64
endif
ifeq ($(config),debug_x32)
  Brimstone_config = debug_x32
  UnitTests_config = debug_x32
endif

PROJECTS := Brimstone UnitTests

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Brimstone:
ifneq (,$(Brimstone_config))
	@echo "==== Building Brimstone ($(Brimstone_config)) ===="
	@${MAKE} --no-print-directory -C . -f Brimstone.make config=$(Brimstone_config)
endif

UnitTests:
ifneq (,$(UnitTests_config))
	@echo "==== Building UnitTests ($(UnitTests_config)) ===="
	@${MAKE} --no-print-directory -C . -f UnitTests.make config=$(UnitTests_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Brimstone.make clean
	@${MAKE} --no-print-directory -C . -f UnitTests.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release_x64"
	@echo "  release_x32"
	@echo "  debug_x64"
	@echo "  debug_x32"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Brimstone"
	@echo "   UnitTests"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"